### ISSUE TITLE
Case sensitivity in usernames

### ISSUE THREAD

**Issue by noahadler** [UK-AS-HIVE/meteor-accounts-ldap#1]
I think that LDAP usernames are [always?] case-insensitive, but the usernames in Meteor Accounts are case-sensitive.  This causes a few problems, such as when users login with different capitalization, a new account might get created.  We should figure out the best way to solve this.

**Comment by mpaddock** [comment]
Probably safe to just push everything to lowercase before the Meteor.users
insert/update. I'm sure there are instances where users are concerned with
the case sensitivity of their usernames, but I'd bet it's rare with LDAP in
general and not an issue for us at all.
