### ISSUE TITLE
Add support for multiple domain user lookup

### ISSUE THREAD

**Issue by noahadler** [UK-AS-HIVE/meteor-accounts-ldap#2]

**Comment by noahadler** [comment]
I'm thinking that converting the serverDc setting from a string to an array of strings (or the option of either one) would be sufficient to cover this.  That is, it's only relevant in the LDAP.search() function.  Does that sound right?

**Comment by mpaddock** [comment]
If we're only interested in lookup, then that would be fine I think - binding to AD should let you search MC. If we're interested in login then the user will need to bind to MC, and we'd need to let Meteor.settings.ldap be an array of objects. Could then search both in succession, or give prefixes as an option?

There are a couple of other things I need to clean up in ldap_server as well.
