### ISSUE TITLE
Atmosphere package outdated

### ISSUE THREAD

**Issue by JanBaunooo** [UK-AS-HIVE/meteor-accounts-ldap#6]
On atmosphere repo (https://atmospherejs.com/tdamsma/meteor-accounts-ldap) version 0.1.0 (with the user not found server crash) is available instead of 0.1.1 on github.

**Comment by mpaddock** [comment]
That's a fork of this package - ours isn't published on atmosphere at all. Their repo is here:

https://github.com/tdamsma/meteor-accounts-ldap/

**Comment by JanBaunooo** [comment]
I'm sorry for my mistake.
